language: php

php:
  - 8.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - php -dxdebug.mode=coverage vendor/phpunit/phpunit/phpunit --coverage-text

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
