name: PHP Composer

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      env:
        XDEBUG_MODE: coverage
      run: php vendor/phpunit/phpunit/phpunit

    - name: Upload coverage results to coveralls.io
      env:
        COVERALLS_RUN_LOCALLY: 1
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        composer global require php-coveralls/php-coveralls
        php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v


    - name: Upload Scrutinizer coverage
      uses: sudo-bot/action-scrutinizer@latest
      with:
        cli-args: "--format=php-clover build/logs/clover.xml"
